/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "projet.h"

bool_t
xdr_date (XDR *xdrs, date *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->jour))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mois))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->annee))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->heure))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->jour);
			IXDR_PUT_LONG(buf, objp->mois);
			IXDR_PUT_LONG(buf, objp->annee);
			IXDR_PUT_LONG(buf, objp->heure);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->jour))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mois))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->annee))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->heure))
				 return FALSE;
		} else {
			objp->jour = IXDR_GET_LONG(buf);
			objp->mois = IXDR_GET_LONG(buf);
			objp->annee = IXDR_GET_LONG(buf);
			objp->heure = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->jour))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mois))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->annee))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->heure))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_personne (XDR *xdrs, personne *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->adherent))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_outil (XDR *xdrs, outil *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anomalie))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_poste (XDR *xdrs, poste *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->description, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_location (XDR *xdrs, location *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->id_personne))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->id_outil))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->id);
		IXDR_PUT_LONG(buf, objp->id_personne);
		IXDR_PUT_LONG(buf, objp->id_outil);
		}
		 if (!xdr_date (xdrs, &objp->date_debut))
			 return FALSE;
		 if (!xdr_date (xdrs, &objp->date_fin))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->id_personne))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->id_outil))
				 return FALSE;

		} else {
		objp->id = IXDR_GET_LONG(buf);
		objp->id_personne = IXDR_GET_LONG(buf);
		objp->id_outil = IXDR_GET_LONG(buf);
		}
		 if (!xdr_date (xdrs, &objp->date_debut))
			 return FALSE;
		 if (!xdr_date (xdrs, &objp->date_fin))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_personne))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_outil))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date_debut))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date_fin))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_param_date (XDR *xdrs, param_date *objp)
{
	register int32_t *buf;

	 if (!xdr_date (xdrs, &objp->date_debut))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date_fin))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_param_outil (XDR *xdrs, param_outil *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id_outil))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_adherent))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date_debut))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date_fin))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_param_poste (XDR *xdrs, param_poste *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id_poste))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_adherent))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date_debut))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date_fin))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_paiement (XDR *xdrs, paiement *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_param_paiement (XDR *xdrs, param_paiement *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id_paiement))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_location))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->type_location))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tab_outils (XDR *xdrs, tab_outils *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->listeOutils, 50,
		sizeof (outil), (xdrproc_t) xdr_outil))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbOutils))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tab_postes (XDR *xdrs, tab_postes *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->listePostes, 50,
		sizeof (poste), (xdrproc_t) xdr_poste))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbPostes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_tab_paiements (XDR *xdrs, tab_paiements *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->listePaiements, 50,
		sizeof (paiement), (xdrproc_t) xdr_paiement))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbPaiements))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_informations (XDR *xdrs, informations *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->tarifs, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->horraires, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
