/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "projet.h"

personne liste_personnes[5];
int nbPersonnes;
outil outils[5];
int nbOutils;
location locations[5];
int nbLocations;
paiement paiements[5];
int nbPaiements;

int *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	//Initialisations des nb tableaux à 0
	nbPersonnes = 0;
	nbOutils = 0;
	nbLocations = 0;

	//Ajout d'un outil
	outil outil_1 = {id:nbOutils, nom:"Marteau",anomalie:0};
	outils[nbOutils] = outil_1;
	nbOutils++;

	//Ajout d'une methode de paiement
	paiement paiement_1 = {id:nbPaiements,nom:"Paypal"};
	paiements[nbPaiements] = paiement_1;
	nbPaiements++;

	result = 1;
	return &result;
}

int *
enregistrer_adherent_1_svc(personne *argp, struct svc_req *rqstp)
{
	static int  result;

	liste_personnes[argp->id] = *argp;
	printf("enregistrement");
	result = 1;
	return &result;
}

int *
renouveler_adherent_1_svc(personne *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

tab_outils *
lister_outils_1_svc(param_date *argp, struct svc_req *rqstp)
{
	static tab_outils result;
	result.nbOutils = 0;
	
	for (int i = 0; i < nbOutils; i++)
	{
		result.listeOutils[i] = outils[i];
		result.nbOutils++;
	}

	return &result;
}

tab_postes *
lister_postes_1_svc(param_date *argp, struct svc_req *rqstp)
{
	static tab_postes  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
louer_outil_1_svc(param_outil *argp, struct svc_req *rqstp)
{
	static int  result;

	//Creation de la location
	location la_location;
    la_location.id = nbLocations; //A changer en fonction de l'emplacement
	la_location.id_personne = argp->id_adherent;
	la_location.id_outil = argp->id_outil;
	la_location.date_debut = argp->date_debut;
	la_location.date_fin = argp->date_fin;
	la_location.type_location = 1;
	la_location.retourner = 0;
	la_location.payer = 0;

	locations[nbLocations] = la_location; //A changer en fonction de l'emplacement
	nbLocations++;
	return &result;
}

int *
reserver_poste_1_svc(param_poste *argp, struct svc_req *rqstp)
{
	static int  result;

	//Creation de la location
	location la_location;
    la_location.id = 0; //A changer en fonction de l'emplacement
	la_location.id_personne = argp->id_adherent;
	la_location.id_outil = argp->id_poste;
	la_location.date_debut = argp->date_debut;
	la_location.date_fin = argp->date_fin;
	la_location.type_location = 2;
	locations[0] = la_location; //A changer en fonction de l'emplacement
	return &result;
}

int *
renouveler_adhesion_1_svc(personne *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

informations *
afficher_tarifs_postes_1_svc(void *argp, struct svc_req *rqstp)
{
	static informations infos;
	strcpy(infos.tarifs,"10€ pour 1h, 30€ pour 4h, et 50€ pour 8h");
	strcpy(infos.horraires,"les jours de la semaine 12h à 14h ou 17h à 19h");
	return &infos;
}

tab_paiements *
afficher_mode_paiement_1_svc(void *argp, struct svc_req *rqstp)
{
	static tab_paiements  result;

	result.nbPaiements = 0;
	for (int i = 0; i < nbPaiements; i++)
	{
		result.listePaiements[i] = paiements[i];
		result.nbPaiements++;
	}
	return &result;
}

int *
effectuer_paiement_1_svc(param_paiement *argp, struct svc_req *rqstp)
{
	static int  result;

	locations[argp->id_location].payer = 1;
	result = 1;
	return &result;
}

int *
retour_location_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	for (int i = 0; i < nbLocations; i++)
	{
		if(locations[i].id_outil == *argp){
			locations[i].retourner == 1;
		}
	}
	

	return &result;
}

int *
signaler_anomalie_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	outils[*argp].anomalie = 1;
	result = 1;
	return &result;
}
