/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "projet.h"

personne liste_personnes[50]; 
outil outils[50];

int *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	//Ajout d'un outil
	outil outil_1 = {id:0, nom:"Marteau",anomalie:0};
	outils[0] = outil_1;
	printf("init");
	result = 1;
	return &result;
}

int *
enregistrer_adherent_1_svc(personne *argp, struct svc_req *rqstp)
{
	static int  result;

	liste_personnes[argp->id] = *argp;
	printf("enregistrement");
	result = 1;
	return &result;
}

int *
renouveler_adherent_1_svc(personne *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

tab_outils *
lister_outils_1_svc(param_date *argp, struct svc_req *rqstp)
{
	static tab_outils result;
	result.nbOutils = 0;
	
	for (int i = 0; i < result.nbOutils; i++)
	{
		if(outils[i].nom != NULL){
			result.listeOutils[i] = outils[i];
			result.nbOutils++;
		}
	}

	return &result;
}

tab_postes *
lister_postes_1_svc(param_date *argp, struct svc_req *rqstp)
{
	static tab_postes  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
louer_outil_1_svc(param_outil *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
reserver_poste_1_svc(param_poste *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
renouveler_adhesion_1_svc(personne *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

informations *
afficher_tarifs_postes_1_svc(void *argp, struct svc_req *rqstp)
{
	static informations infos;
	strcpy(infos.tarifs,"10€ pour 1h, 30€ pour 4h, et 50€ pour 8h");
	strcpy(infos.horraires,"les jours de la semaine de 12h à 14h ou de 17h à 19h, et tous les samedis de 14h à 18h");
	return &infos;
}

tab_paiements *
afficher_mode_paiement_1_svc(void *argp, struct svc_req *rqstp)
{
	static tab_paiements  result;

	result.nbPaiements = 0;

	

	return &result;
}

int *
effectuer_paiement_1_svc(param_paiement *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retour_location_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
signaler_anomalie_1_svc(outil *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
