/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "projet.h"


void
geom_prog_1(char *host)
{
	CLIENT *clnt;
	int  *resultat;
	void *vide;

	//Informations client
	personne client;
	client.id = 0;
	strcpy(client.prenom,"Jean");
	strcpy(client.nom,"Maurice");
	client.adherent = 1;

#ifndef	DEBUG
	clnt = clnt_create (host, GEOM_PROG, GEOM_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("CLIENT : \n");
	resultat = init_1(vide,clnt);

	//INIT
	if (resultat == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else printf("Initialisation réussie(code : %d) \n",*resultat);

	//Enregistrer adhérent

	resultat = enregistrer_adherent_1(&client, clnt);
	if (resultat == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else printf("Enregistrement réussie(code : %d) \n",*resultat);
	/*
	result_3 = renouveler_adherent_1(&renouveler_adherent_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	result_4 = lister_outils_1(&lister_outils_1_arg, clnt);
	if (result_4 == (tab_outils *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = lister_postes_1(&lister_postes_1_arg, clnt);
	if (result_5 == (tab_postes *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = louer_outil_1(&louer_outil_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = reserver_poste_1(&reserver_poste_1_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = renouveler_adhesion_1(&renouveler_adhesion_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = afficher_tarifs_postes_1((void*)&afficher_tarifs_postes_1_arg, clnt);
	if (result_9 == (informations *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = afficher_mode_paiement_1((void*)&afficher_mode_paiement_1_arg, clnt);
	if (result_10 == (informations *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = effectuer_paiement_1(&effectuer_paiement_1_arg, clnt);
	if (result_11 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = retour_location_1(&retour_location_1_arg, clnt);
	if (result_12 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = signaler_anomalie_1(&signaler_anomalie_1_arg, clnt);
	if (result_13 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	geom_prog_1 (host);
exit (0);
}
